application: evalert1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /.*
  script: evictalert.application

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6
